appname = flight-api
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 
ES_LOCAL_API_KEY=LVc5RGFKUUI5Unk0NXBFdUZCMHg6YXNqc3p6aXBSWG1KS2ctUThrTlFrdw==
ES_LOCAL_URL=http://localhost:9200
