appname = flight-api
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 
ES_LOCAL_API_KEY=QnZnMjdwUUJfZXVoNWRBbE1MaTg6c19PM0hWUVFRay1QM0QyLXNuWE1fZw==
ES_LOCAL_URL=http://elasticsearch:9200
